FROM node:20-alpine AS builder

WORKDIR /app

COPY backend/package*.json ./backend/
COPY prisma/schema.prisma ./prisma/

WORKDIR /app/backend
RUN npm ci

COPY backend ./
RUN npm run build
RUN npx prisma generate --schema=../prisma/schema.prisma

EXPOSE 5000

CMD ["node", "dist/server.js"]
